# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michel de Bree
email: michel@micheldebree.nl
description: Full Stack Java Developer
tagline: independent, experienced and agile
host: 0.0.0.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.micheldebree.nl" # the base hostname & protocol for your site
twitter_username: micheldebree
github_username: micheldebree

# Build settings
markdown: kramdown
sass:
  style: compressed
