[personal]
first_name = "Michel"
last_name = "de Bree"
profile_image = "logo-mono.svg"
language = "nl"
include_icons = true

[personal.info]
address = "Nootdorp, NL"
telephone = "+31 681 473 884"

[personal.info.email]
link = "mailto:michel@micheldebree.nl"
label = "michel@micheldebree.nl"

[personal.info.linkedin]
link = "https://linkedin.com/in/micheldebree"
label = "linkedin.com/in/micheldebree"

[personal.info.website]
link = "https://www.micheldebree.nl"
label = "www.micheldebree.nl"

[personal.info.github]
link = "https://github.com/micheldebree"
label = "github.com/micheldebree"


[personal.icon]
address = "house"
telephone = "phone"
email = "envelope"
linkedin = "linkedin"
github = "github"
homepage = "globe"
website = "globe"

[section.icon]
education = "graduation-cap"
experience = "briefcase"
languages = "language"
other_experience = "wrench"
personal = "brain"
profile = "id-card"
references = "users"
skills = "cogs"

# To change fill_color to white, replace value with "#ffffff"
[layout]
# fill_color = "#ffffff"
fill_color = "#f4f1eb"
paper_size = "a4"
accent_color = "#d4d2cc"
# deafult value is 71%
left_pane_width = "71%"

[layout.text]
font = "Inter"
# font = "Jost"
# font = "Urbanist"
# font = "Space Grotesk"
size = "10pt"
cover_letter_size = "11pt"

[layout.text.color]
light = "#ededef"
medium = "#78787e"
dark = "#3c3c42"

[language.nl]
subtitle = "rvaren, pragmatische ontwikkelaar met een scherp oog voor kwaliteit."

[language.en]
subtitle = "Ingeniero de software con un talento para soluciones de IA amigables para humanos"

[import]
fontawesome = "@preview/fontawesome:0.5.0"
