[Personal]
Name.First = "Michel"
Name.Last = "de Bree"
Title = "Java Developer"
YearOfBirth = 1972
Residence = "Nootdorp"
Languages = ["Nederlands (moedertaal)", "Engels (fluent)"]

[Summary]
Tagline.nl = "Ervaren Java ontwikkelaar met een scherp oog voor kwaliteit"
Introduction = """
Mijn grootste uitdaging als software engineer is het beheersbaar houden van complexiteit. \
Met meer dan 20 jaar ervaring is het schrijven van inzichtelijke, robuuste code inmiddels een basis hygiëne voor me. \
Ruim 15 jaar ervaring met Java, met minstens 10 jaar in complexe, missie-kritische systemen. \
Naast coderen werk ik daarom ook \
nauw samen met eindgebruikers, architecten, platform experts en leveranciers om een doeltreffende, betrouwbare en efficiënte oplossing boven tafel te krijgen. \
Ik heb hiervoor een scherpe, krititisch blik onwikkeld, die ik goed kan balanceren met een pragmatische houding. \
Hierdoor kan ik risico's vroegtijdig identificeren en de impact van \
veranderingen op de langere termijn inschatten.

Naast mijn werk breng ik tijd door met mijn vrouw en tienerzoon, vind ik het \
leuk om buiten te zijn, te koken en cultuur te snuiven in het buitenland. Ook \
houd ik me af en toe bezig met meer creatieve toepassingen van computers in de \
zogenaamde Demoscene.
"""

[[Links]]
Name = "Email"
Url = "michel@micheldebree.nl"

[[Links]]
Name = "Website"
Url = "https://www.micheldebree.nl"

[[Links]]
Name = "LinkedIn"
Url = "https://nl.linkedin.com/in/micheldebree"

[[Keywords]]

[[Keywords.Java]]
Name = "Java"
Url = "https://www.java.com"

[[Keywords.SpringBoot]]
Name = "Spring Boot"
Url = "https://www.java.com"

[[Experience]]

Title.nl = "Regelsysteem en services voor regelgeving m.b.t. de Omgevingswet"
Company = "Digitaal Stelsel Omgevingswet (Rijkswaterstaat)"
Location = "Rotterdam"
Start = "2018"
End = "2025"

Situation.nl = """
Eén van de centrale onderdelen van het Digitaal Stelsel Omgevingswet, is de Toepasbare Regels component. \
Deze applicatie ontvangt regelgeving afkomstig van gemeentes, provincieen, waterschappen en het rijk, in een open standaard formaat. \
Met deze regels worden automatisch dynamische vragenlijsten \
opgesteld voor de eindgebruikers. De ingevulde vragen worden realtime doorgerekend door een rule-engine, en leiden tot een advies \
of vergunningaanvraag. Deze functionaliteit wordt aangeboden op het landelijke Omgevingswet loket, \
maar is ook d.m.v. open REST API's te gebruiken door iedereen die hier functionaliteit op wil bouwen.
Vanwege het publieke karakter en de grote gebruikersgroep worden er hoge eisen \
gesteld aan betrouwbaarheid, beschikbaarheid, veiligheid en schaalbaarheid.
"""


[[Experience.Task.nl]]
Task = "Nieuwbouw van kernfunctionaliteit."
Action = """
Het ontwerp en de bouw van het synchronisatiemechanisme dat stamdata up-to-date houd met de externe bron.\
"""
Result = """
De ontwerpkeuzes die ik hierbij gemaakt hebben gezorgd dat dit mechanisme sinds \
inwerkingtreding betrouwbaar en zonder noemenswaardige problemen werkt. Ook \
heeft de eenvoudige maar robuuste opzet in de praktijk al meerdere malen \
eenvoudig dataherstel mogelijk gemaakt.
"""
Keywords = ["Java", "Spring Boot"]

[[Experience.Task.nl]]
Task = "Ontwerpen, afstemmen en bouwen van REST (HAL+JSON) API's met gebruikers en architecten, d.m.v. OpenAPI (Swagger) specificaties"
Action = "Het herontwerp van een API om met behulp van HAL+JSON gegevens fijnmaziger en gepagineerd op te leveren"
Result = "API calls en database acties zijn daardoor kortlopend en schaalbaar, waardoor het systeem minder belast wordt, en de throttling die we hadden ingesteld kon worden opgeheven"

[[Experience.Task.nl]]
Task = "Ontwerpen en afstemmen met gebruikers, business analysten en architecten van nieuwe functionaliteiten"
Action = """
Bij een migratietraject van de integratie van onze applicatie in het \
overkoepelende portaal, ben ik op eigen initiatief met gebruikers gaan praten \
over de impact. \
Na doorvragen bleek dat de geïntegreerde versie nagenoeg niet werd gebruikt, en heb ik met de architect overlegd over de noodzaak van deze integratie.\
"""
Result = """Uitkomst was dat wij het wekenlange traject voor onze applicatie \
niet zijn ingegaan, en de ongebruikte integratielogica hebben verwijderd.
"""

[[Experience.Task.nl]]
Task = "Bewaken van code kwaliteit"
Action = """
Ik en mijn team zijn scherp op code reviews en de definition of done die we
afgesproken hebben. Hierin zijn zaken opgenomen als testcoverage, code style,
regressietests en aantal SonarQube issues. De applicaties van alle teams worden
extern geaudit op onderhoudbaarheid en veiligheid door de Software Improvement
Group, waarvan ik tooling heb geintegreerd in onze Gitlab CI pipeline.
Periodiek vertegenwoordig ik ons team om issues te bespreken met de SIG.\
"""
Result = """Als gevolg komen er bij de SIG overleggen geen noemenswaardige \
isssues aan het licht. Ook hoeven we zelden een noodreparatie te doe op de \
productie omgeving
"""

[[Experience]]

Title.nl = "Knooppunt voor API toegang en autorisatie"
Company = "Digitaal Stelsel Omgevingswet (Rijkswaterstaat)"
Location = "Den Haag, Rotterdam"
Start = "2016"
End = "2018"

Situation.nl = """
Binnen het Digitaal Stelsel Omgevingswet worden alle API's aangeboden via het
Knooppunt. Ook biedt het Knooppunt authenticatie m.b.v. DigID, eHerkenning,
OAuth, API keys en PKIO certificaten. Communicatie tussen componenten binnen en
buiten het stelsel loopt via het Knooppunt, waardoor zaken als routering,
logging, foutafhandeling, throttling en beveiliging centraal geregeld zijn.
Ook biedt het Knooppunt een open stelsel voor derden waar API's afgenomen worden door iedereen.

Omdat het DSO destijds min of meer "launching customer" was van het Standaard Platform, ben ik 
in een overgangsperiode geleidelijk overgegaan van mijn rol bij het Standaard Platform naar full time aan de slag bij het DSO.

"""

[[Experience.Task.nl]]
Task = "Lead development"
Action = """Bij de start van het project ben ik begonnen als één van de drie \
ontwikkelaars. In de loop van de tijd is mijn rol op een organische manier \
uitgegroeid tot lead developer in een team van wisselende samenstelling. 
"""

[[Experience.Task.nl]]
Task = "Integratie development"
Action = """Het ontwikkelen van nieuwe componenten en uitbreidingen op het standaard open source product WSO2, in Java en Spring Boot.
Voorbeeld: een adapter om API keys te kunnen gebruiken voor afnemers in het
open stelsel. De adapter gebruikt achter de schermen OAuth2 authtenticatie om
aan te kunnen sluiten op WSO2.
"""

[[Experience.Task.nl]]
Task = "Interim Scrum Master"
Action = "Bij de start van het project werd ik gevraagd ook de rol van Scrum Master op me te nemen. Naast het organiseren vertegenwoordigde ik ons team in de afstemming met andere teams in Scrum-of-scrums."
Result = "De rol van vertegenwoordiger en aanspreekpunt heeft veel overlap met die van lead developer. Ik heb wel gemerkt dat ik de tijd en energie die gaat zitten in het coachen van een Scrum team, liever in andere zaken steek. Bij het groeien van het team kon ik de rol daarom met plezier overdragen."

[[Experience.Task.nl]]
Task = "CI/CD, DevOps development"
Action = "Het ontwikkelen van scripting voor het uitrollen van de applicatie. Tijdens het project maakte het Standaard Platform ook grote ontwikkelingen door, via een Docker Swarm oplossing naar uiteindelijk Kubernetes en Openshift. Hierdoor was het uitrollen van applicaties ook een belangrijk en dynamisch onderdeel van de ontwikkeling van applicaties binnen het DSO."


[[Experience]]
Title.nl = "Standaard Platform voor overheid applicaties"
Company = "Ministerie van Infrastructuur en Waterstaat"
Location = "Den Haag"
Start = "2015"
End = "2018"

Situation.nl = """
Het Standaard Platform is op dit moment een standaard, schaalbaar
containerplatform voor overheid applicaties. In mijn huidige project is dit het
onderliggende platform waar de Omgevingswet applicaties op draaien. Toen ik
begon was het Standaard Platform een complete standaard enterprise architectuur
die volledige automatisch uitgerold kon worden, met daarin ook zelfbouw
componenten en CI/CD functionaliteit. Maar zonder containerization. Tijdens mij
werk bij, en met het Standaard Platform heeft het een ontwikkeling doorgemaakt
tot het op Kubernetes gebaseerde platform dat het nu is.
"""

[[Experience.Task.nl]]
Task = "Ontwikkeling van custom componenten en uitbreidingen."
Action = "Bouw, in team verband, generieke platform componenten voor uitrol, authenticatie en integratie. M.b.v Java en WSO2"

[[Experience.Task.nl]]
Task = "Ontwikkeling van automatische uitrol en provisioning scripting."
Action = "Bouw, in team verband, m.b.v. Ruby, Linux shell en Amazon EC2."
Result = "Met de tool kon in minder dan een uur tijd een compleet applicatieplatform worden uitgerold op Amazon EC2 dat klaar was voor het hosten en de lifecycle management van een complete enterprise applicatie"

[[Experience]]
Title.nl = "Online authenticatie"
Company = "ING"
Location = "Amsterdam"
Start = "2014"
End = "2015"

Situation.nl = """
In mijn eerste opdracht als freelancer was ik onderdeel van een Scrum/DevOps team.
Eén van de functionaleiten die we in dit team naar productie gebracht hebben,
is de "gebruikersnaam vergeten" functionaliteit voor online bankieren.
"""

[[Experience.Task.nl]]
Task = "Backend-  en integratie ontwikkeling"
Action = "Java, Spring"

[[Experience.Task.nl]]
Task = "Frontend ontwikkeling"
Action = "Angular"

[[Experience]]
Title.nl = "Begonnen als ZZP-er"
Company = "micheldebree.nl"
Location = "Den Haag"
Start = "2014"

Situation.nl = """
In 2014 ben ik begonnen als ZZP-er om meer vrijheid en focus in mijn werk aan te brengen. Vanaf 2014 voer ik mijn opdrachten uit als ZZP-er.
"""

[[Experience]]
Title.nl = "Senior Software Engineer"
Company = "E-ID"
Location = "Vianen"
Start = "2005"
End = "2014"

[[Experience]]
Title.nl = "Software Engineer"
Company = "PaC/Imtech ICT"
Location = "Den Haag"
Start = "2001"
End = "2005"

[[Experience]]
Title.nl = "Ontwikkelaar"
Company = "Leids Universitair Medisch Centrum"
Location = "Leiden"
Start = "1994"
End = "2001"

Situation.nl = "Tijdens mijn studie informatica in Delft werkte ik parttime voor het LUMC."

[[Experience.Task.nl]]
Task = "Ontwikkeling van een systeem voor multimedia examens"
Action = """
Samen met een andere student en een chirurg met ontwikkelaars-aspiraties deed ik het ontwikkelwerk van een nieuw systeem om \
examens te kunnen samenstellen, en af te nemen bij studenten van het LUMC.\
"""
Result = "Het systeem ondersteunt foto's, filmpjes en geluidsopnamen als onderdeel van de vraag."

[[Experience.Task.nl]]
Task = "Onderhoud van wetenschappelijke software"
Action = """
De software ondersteunde het onderzoek naar de biologische klok onder leiding \
van een hoogleraar. Enerzijds werden kunstmatige dag/nacht cycli gegenereerd \
door lampen aan te sturen vanuit een custom applicatie. Anderszijds werden \
bewegingen van kevers geregistreerd met sensors. De resultaten moesten \
periodiek in een speciale grafische representatie worden uitgeprint uit de \
software.
"""


# === Education

[[Education]]
Start = "1991"
End = "1998"
Title.nl = "Technische Informatica"
Institution.nl = "Technische Universiteit Delft"

[[Education]]
Start = "1984"
End = "1991"
Title.nl = "VWO beta"
Institution.nl = "Het Vlietland College Leiden"

# Skills are scored 1-10

[[Skills]]
Category = "Programmeertalen"

[[Skills.Subject]]
Name = "Java 21"
Score = 9

[[Skills.Subject]]
Name = "Javascript"
Score = 8

[[Skills.Subject]]
Name = "Typescript"
Score = 7

[[Skills.Subject]]
Name = "Bash"
Score = 7

# ===

[[Skills]]
Category = "Frameworks"

# ===

[[Skills.Subject]]
Name = "Spring Boot"
Score = 9

[[Skills.Subject]]
Name = "Hibernate"
Score = 9

[[Skills.Subject]]
Name = "PostgreSQL"
Score = 8

[[Skills.Subject]]
Name = "Elasticsearch"
Score = 7

[[Skills.Subject]]
Name = "Liquibase"
Score = 8

[[Skills.Subject]]
Name = "React"
Score = 7

[[Skills]]
Category = "Integratie"

[[Skills.Subject]]
Name = "REST"
Score = 9

[[Skills.Subject]]
Name = "OpenAPI"
Score = 8

[[Skills.Subject]]
Name = "HAL+JSON"
Score = 8

[[Skills.Subject]]
Name = "SOAP"
Score = 6

[[Skills.Subject]]
Name = "OAuth"
Score = 7

[[Skills.Subject]]
Name = "JWT"
Score = 6

[[Skills]]
Category = "DevOps"

[[Skills.Subject]]
Name = "Gitlab CI"
Score = 7

[[Skills.Subject]]
Name = "Kubernetes"
Score = 8

[[Skills.Subject]]
Name = "OpenShift"
Score = 6

[[Skills.Subject]]
Name = "Docker"
Score = 8

[[Skills.Subject]]
Name = "Linux"
Score = 8

[[Skills.Subject]]
Name = "Helm"
Score = 8

[[Skills.Subject]]
Name = "Kibana"
Score = 3

[[Skills.Subject]]
Name = "Grafana"
Score = 3

[[Skills.Subject]]
Name = "Scrum"
Score = 9

[[Skills.Subject]]
Name = "Agile SAFe"
Score = 6

[[Skills]]
Category = "Testen"

[[Skills.Subject]]
Name = "Junit"
Score = 9

[[Skills.Subject]]
Name = "Mockito"
Score = 8

[[Skills.Subject]]
Name = "Cucumber"
Score = 8

[[Skills.Subject]]
Name = "Selenium"
Score = 4

[[Skills.Subject]]
Name = "Wiremock"
Score = 8

[[Skills.Subject]]
Name = "JMeter"
Score = 6

[[Skills.Subject]]
Name = "Jest"
Score = 7

#
# [[Skills]]
# Name = "DMN"
# Url = "https://www.omg.org/dmn/"
#
# [[Skills]]
# Name = "Drools"
# Url = "https://drools.org/"
#
# [[Skills]]
# Name = "Kubernetes"
# Url = "https://kubernetes.io"
#
# [[Skills]]
# Name = "Openshift"
# Url = "https://www.openshift.com"
#
# [[Skills]]
# Name = "Helm"
# Url = "https://helm.sh"
#
# [[Skills]]
# Name = "Docker"
# Url = "https://www.docker.com"
#
# [[Skills]]
# Name = "Linux"
# Url = "https://www.linux.org"
#
# [[Skills]]
# Name = "JUnit"
# Url = "https://junit.org/junit5"
#
# [[Skills]]
# Name = "Mockito"
# Url = "https://site.mockito.org"
#
# [[Skills]]
# Name = "Jest"
# Url = "https://jestjs.io"
#
# [[Skills]]
# Name = "Chai"
# Url = "https://www.chaijs.com"
#
# [[Skills]]
# Name = "Wiremock"
# Url = "http://wiremock.org"
#
# [[Skills]]
# Name = "Cucumber"
# Url = "https://cucumber.io"
#
# [[Skills]]
# Name = "Selenium"
# Url = "https://www.selenium.dev"
#
# [[Skills]]
# Name = "JMeter"
# Url = "https://jmeter.apache.org"
#
# [[Skills]]
# Name = "Git"
# Url = "https://git-scm.com"
#
# [[Skills]]
# Name = "Gitlab"
# Url = "https://about.gitlab.com"
#
# [[Skills]]
# Name = "Maven"
# Url = "https://maven.apache.org"
#
# [[Skills]]
# Name = "JIRA"
# Url = "https://www.atlassian.com/software/jira"
#
# [[Skills]]
# Name = "Confluence"
# Url = "https://www.atlassian.com/software/confluence"
#
# [[Skills]]
# Name = "SonarQube"
# Url = "https://www.sonarqube.org"
